base:
  project: learn_ml
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_clean.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.20

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 50
      min_samples_split: 2

model_path: models/models.joblib

# reports:
#   params: reports/params.json
#   score: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: insurance
  run_name: mlops
  registered_model_name: RandomForestRegressor
  remote_server_uri: http://127.0.0.1:5000